### ISSUE TITLE
Make a mockup of the UI

### ISSUE THREAD

**Issue by pconrad** [ucsb-cs56-webapps/ucsb-cs56-gogaucho#3]
Get the code from https://github.com/ucsb-cs56-pconrad/sparkjava-mustache-example-02 and incorporate the mustache templates into your webapp.

Then, go into the file src/main/resources/templates/nav.mustache and change the navigation menu so that it has options that make sense for your minimum viable product webapp.

Then, add "dummy routes" for each of those, and form elements that have the fields a user would need to enter.   You can follow the "Add Student" and "addedStudent.mustache" as examples.

If this is done by Friday, the participants get 200 points (each member that meaningfully contributes to the effort.)

**Comment by RPaul3** [comment]
Finished navigation bar layout.

**Comment by zhykoties** [comment]
Approved, estimate: 200 points
